### ISSUE TITLE
great library 

### ISSUE THREAD

**Issue by bacloud23** [mrseanryan/image-checker#6]
I just wanted to thank you very much for this library! 
it is very useful. 

later I will be checking how it works in my web-app I'm building. 

Otherwise, what is the current status of it's development? 
everything stable? tested lately? with later node engines? 

thanks a lot!

**Comment by mrseanryan** [comment]
hello Ba

thank you for your interest however, this project is not really implemented yet.

As this is mentioned in the readme and in the other issue, I will be closing this issue. Thank you

**Comment by mrseanryan** [comment]
see #3
